version: "3.8"

services:
  client:
    container_name: client
    image: boj-client-img
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - ./client/.env

  server:
    image: boj-server-img
    container_name: server
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
      - redis
    env_file:
      - ./server/.env
    environment:
      - DB_HOSTNAME=mysql
      - REDIS_HOSTNAME=redis

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./server/.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - client
      - server

  redis:
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
