version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - '4173:4173'

  server:
    container_name: server
    build:
      context: ./server
    environment:
      - name=value
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
      - DB_USERNAME=bojrooms
      - DB_PASSWORD=bojroomssecret123!@#
      - DB_NAME=bojrooms
    ports:
      - '4000:4000'
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: bojrooms
      MYSQL_USER: bojrooms
      MYSQL_PASSWORD: bojroomssecret123!@#
      MYSQL_ROOT_PASSWORD: bojroomssecret123!@#
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
