GET localhost:4000/hello/world?name=John

###

POST localhost:4000/auth/mock
Content-Type: application/json

{
  "username": "mock1",
  "password": "mock1"
}

###
POST localhost:4000/auth/mock
Content-Type: application/json

{
  "username": "mock2",
  "password": "mock2"
}

###

POST localhost:4000/auth/mock
Content-Type: application/json

{
  "username": "mock_unauthorized",
  "password": "mock_unauthorized"
}

###

GET localhost:4000/auth/logout
