import { Tag } from '../src/types/Tag';
export const constTags: Tag[] = [
  { id: 96, name: '수학' },
  { id: 12, name: '구현' },
  { id: 24, name: '다이나믹 프로그래밍' },
  { id: 134, name: '자료 구조' },
  { id: 13, name: '그래프 이론' },
  { id: 15, name: '그리디 알고리즘' },
  { id: 55, name: '문자열' },
  { id: 78, name: '브루트포스 알고리즘' },
  { id: 14, name: '그래프 탐색' },
  { id: 140, name: '정렬' },
  { id: 18, name: '기하학' },
  { id: 141, name: '정수론' },
  { id: 165, name: '트리' },
  { id: 109, name: '애드 혹' },
  { id: 92, name: '세그먼트 트리' },
  { id: 127, name: '이분 탐색' },
  { id: 83, name: '사칙연산' },
  { id: 104, name: '시뮬레이션' },
  { id: 20, name: '너비 우선 탐색' },
  { id: 184, name: '해 구성하기' },
  { id: 21, name: '누적 합' },
  { id: 143, name: '조합론' },
  { id: 47, name: '많은 조건 분기' },
  { id: 19, name: '깊이 우선 탐색' },
  { id: 149, name: '최단 경로' },
  { id: 81, name: '비트마스킹' },
  { id: 185, name: '해시를 사용한 집합과 맵' },
  { id: 31, name: '데이크스트라' },
  { id: 62, name: '백트래킹' },
  { id: 169, name: '트리를 사용한 집합과 맵' },
];
